# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-03 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_auto_20160624_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdIOBasedTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interface.TestCase')),
                ('expected_input', models.TextField(blank=True, default=None, null=True)),
                ('expected_output', models.TextField(default=None)),
                ('weight', models.IntegerField(default=1.0)),
            ],
            bases=('interface.testcase',),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='codequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='input',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='output',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='no_of_inputs',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='no_of_outputs',
        ),
        migrations.AddField(
            model_name='question',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.CharField(default='None', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='code', max_length=24),
        ),
        migrations.AddField(
            model_name='testcase',
            name='type',
            field=models.CharField(default='stdiobasedtestcase', max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='language',
            field=models.CharField(default='python', max_length=24),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.Question'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='CodeQuestion',
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
