# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20180303_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='question',
            name='originality',
            field=models.CharField(choices=[('original', 'Original Question'), ('adopted', 'Adopted Question')], default='original', max_length=24),
        ),
    ]
